apiVersion: v1
kind: Pod
metadata:
  name: hostaliases-pod
spec:
  restartPolicy: Never
  hostAliases:
  - ip: "192.168.100.82"
    hostnames:
    - "gitlab.home.lan"
  - ip: "192.168.100.84"
    hostnames:
    - "jenkns.home.lan"
  containers:
  - name: cat-hosts
    image: busybox
    command:
    - cat
    args:
    - "/etc/hosts"
