apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["deployment:gitlab:gitlab"]'
    workload.cattle.io/targetWorkloadIdNoop: "true"
    workload.cattle.io/workloadPortBased: "true"
  labels:
    cattle.io/creator: norman
  name: gitlab-nodeport
  namespace: gitlab
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: gitlab-http
    nodePort:
    port: 80
    protocol: TCP
    targetPort: 80
  - name: gitlab-https
    nodePort:
    port: 443
    protocol: TCP
    targetPort: 443
  - name: gitlab-ssh
    nodePort:
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-gitlab-gitlab
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
