apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-gitlab-gitlab
  name: gitlab
  namespace: gitlab
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-gitlab-gitlab
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-gitlab-gitlab
    spec:
      affinity: {}
      containers:
      - image: gitlab/gitlab-ce@sha256:6916996c5174a61949ba21d11bfa05c39bf70578c9e9d34eb7ea3e4e87e60dd3
        imagePullPolicy: IfNotPresent
        name: container-0
        ports:
        - containerPort: 22
          name: gitlab-ssh
          protocol: TCP
        - containerPort: 80
          name: gitlab-http
          protocol: TCP
        - containerPort: 443
          name: gitlab-https
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/opt/gitlab
          name: gitlab-data
        - mountPath: /var/log/gitlab
          name: gitlab-logs
        - mountPath: /etc/gitlab
          name: gitlab-config
      dnsConfig: {}
      dnsPolicy: ClusterFirst
      hostAliases:
      - hostnames:
        - gitlab.home.lan
        ip: 10.10.10.82
      - hostnames:
        - jenkins.home.lan
        ip: 10.10.10.84
      - hostnames:
        - registry.home.lan
        ip: 10.10.10.90
      - hostnames:
        - drone.home.lan
        ip: 10.10.10.86
      nodeName: node1
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: gitlab-config
        persistentVolumeClaim:
          claimName: gitlab-config
      - name: gitlab-data
        persistentVolumeClaim:
          claimName: gitlab-data
      - name: gitlab-logs
        persistentVolumeClaim:
          claimName: gitlab-logs
