apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      cattle.io/creator: norman
      workload.user.cattle.io/workloadselector: deployment-gitlab-gitlab
    name: gitlab
    namespace: gitlab
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        workload.user.cattle.io/workloadselector: deployment-gitlab-gitlab
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
      type: RollingUpdate
    template:
      metadata:
        labels:
          workload.user.cattle.io/workloadselector: deployment-gitlab-gitlab
      spec:
        containers:
        - image: gitlab/gitlab-ce:latest
          imagePullPolicy: Always
          name: gitlab
          ports:
          - containerPort: 80
            name: gitlab-http
            protocol: TCP
          - containerPort: 443
            name: gitlab-https
            protocol: TCP
          - containerPort: 22
            name: gitlab-ssh
            protocol: TCP
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          volumeMounts:
          - mountPath: /var/opt/gitlab
            name: gitlab-data
          - mountPath: /var/log/gitlab
            name: gitlab-logs
          - mountPath: /etc/gitlab
            name: gitlab-config
        dnsPolicy: ClusterFirst
        hostAliases:
        - hostnames:
          - jenkins.home.lan
          ip: 192.168.100.84
        - hostnames:
          - registry.home.lan
          ip: 192.168.100.85
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: gitlab-data
          persistentVolumeClaim:
            claimName: gitlab-data
        - name: gitlab-logs
          persistentVolumeClaim:
            claimName: gitlab-logs
        - name: gitlab-config
          persistentVolumeClaim:
            claimName: gitlab-config
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
