apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
  name: gitlab-config
spec:
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: gitlab-config
    namespace: gitlab
  nfs:
    path: /mnt/STORAGE/GITLAB/config
    server: 10.10.10.61
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem