apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["deployment:gitlab:gitlab"]'
    workload.cattle.io/targetWorkloadIdNoop: "true"
    workload.cattle.io/workloadPortBased: "true"
  labels:
    cattle.io/creator: norman
  name: gitlab-nodeport
  namespace: gitlab
  ownerReferences:
  - apiVersion: apps/v1beta2
    controller: true
    kind: deployment
    name: gitlab
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: gitlab-http
    nodePort: 31539
    port: 80
    protocol: TCP
    targetPort: 80
  - name: gitlab-https
    nodePort: 30477
    port: 443
    protocol: TCP
    targetPort: 443
  - name: gitlab-ssh
    nodePort: 32172
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    workload.user.cattle.io/workloadselector: deployment-gitlab-gitlab
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
