apiVersion: v1
kind: Service
metadata:
  name: gitlab-runner
  namespace: gitlab
spec:
  ports:
  - name: runner-gitlab-runner
    port: 8093
    protocol: TCP
    targetPort: 8093
  sessionAffinity: None
  type: NodePort
