apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 2
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-jenkins-jenkins-head
  name: jenkins-head
  namespace: jenkins
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-jenkins-jenkins-head
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-jenkins-jenkins-head
    spec:
      affinity: {}
      containers:
      - env:
        - name: JAVA_HOME
          value: -Dhudson.footerURL=http://jenkins.home.lan
        image: jdfant/jenkins-head@sha256:4938a66feae389bf24004cea26bac61f2694f4ce75a1ad1a3fd1c493d3f243af
        imagePullPolicy: IfNotPresent
        name: container-0
        ports:
        - containerPort: 8080
          name: jweb
          protocol: TCP
        - containerPort: 50000
          name: jbuild
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-head
      dnsConfig:
        nameservers:
        - 10.10.10.90
        searches:
        - home.lan
      dnsPolicy: ClusterFirst
      hostAliases:
      - hostnames:
        - gitlab.home.lan
        ip: 10.10.10.82
      - hostnames:
        - jenkins.home.lan
        ip: 10.10.10.84
      - hostnames:
        - registry.home.lan
        ip: 10.10.10.90
      nodeName: rancho
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: jenkins-head
        persistentVolumeClaim:
          claimName: jenkins-head
