apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      cattle.io/creator: norman
      workload.user.cattle.io/workloadselector: deployment-jenkins-jenkins
    name: jenkins
    namespace: jenkins
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        workload.user.cattle.io/workloadselector: deployment-jenkins-jenkins
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
      type: RollingUpdate
    template:
      metadata:
        labels:
          workload.user.cattle.io/workloadselector: deployment-jenkins-jenkins
      spec:
        containers:
        - env:
          - name: JAVA_OPTS
            value: -Dhudson.footerURL=http://jenkins.home.lan
          image: registry.home.lan/jenkins:latest
          imagePullPolicy: Always
          name: jenkins
          ports:
          - containerPort: 8080
            name: jweb
            protocol: TCP
          - containerPort: 50000
            name: jbuild
            protocol: TCP
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          volumeMounts:
          - mountPath: /var/jenkins_home
            name: jenkins-home
        dnsConfig: {}
        dnsPolicy: ClusterFirst
        hostAliases:
        - hostnames:
          - gitlab.home.lan
          ip: 192.168.100.82
        - hostnames:
          - registry.home.lan
          ip: 192.168.100.85
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-home
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
