apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
  - kubernetes.io/pv-protection
  name: jenkins-head
spec:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: jenkins-head
    namespace: jenkins
  nfs:
    path: /mnt/STORAGE/jenkins
    server: 10.10.10.61
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem