apiVersion: v1
kind: Service
metadata:
  labels:
    cattle.io/creator: norman
  name: jenkins-nodeport
  namespace: jenkins
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: jweb
    nodePort:
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: jbuild
    nodePort:
    port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-jenkins-jenkins-head
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
