apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-jenkins-jenkins-agent
  name: jenkins-agent
  namespace: jenkins
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-jenkins-jenkins-agent
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-jenkins-jenkins-agent
    spec:
      affinity: {}
      containers:
      - env:
        - name: JENKINS_SECRET
          valueFrom:
            secretKeyRef:
              key: JENKINS_SECRET
              name: jenkins-secret
        - name: JENKINS_AGENT_NAME
          valueFrom:
            configMapKeyRef:
              key: JENKINS_AGENT_NAME
              name: jenkins-agent
              optional: false
        - name: JENKINS_AGENT_WORKDIR
          valueFrom:
            configMapKeyRef:
              key: JENKINS_AGENT_WORKDIR
              name: jenkins-agent
              optional: false
        - name: JENKINS_JNLP_URL
          valueFrom:
            configMapKeyRef:
              key: JENKINS_JNLP_URL
              name: jenkins-agent
              optional: false
        - name: JENKINS_URL
          valueFrom:
            configMapKeyRef:
              key: JENKINS_URL
              name: jenkins-agent
              optional: false
        image: jdfant/jenkins-agent@sha256:958c63f4de0fbd229523db2c75ddb00dbfcb8fe16805f91dd9f3c0ba0a1575df
        imagePullPolicy: IfNotPresent
        name: container-0
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-agent
      dnsConfig:
        nameservers:
        - 10.10.10.90
        searches:
        - home.lan
      dnsPolicy: ClusterFirst
      hostAliases:
      - hostnames:
        - gitlab.home.lan
        ip: 10.10.10.82
      - hostnames:
        - jenkins.home.lan
        ip: 10.10.10.84
      - hostnames:
        - registry.home.lan
        ip: 10.10.10.90
      nodeName: node1
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: jenkins-agent
        persistentVolumeClaim:
          claimName: jenkins-agent
