---
    # Source: gitlab-runner/templates/deployment.yaml
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: gitlab-runner-gitlab-runner
      labels:
        app: gitlab-runner-gitlab-runner
        chart: gitlab-runner-0.21.1
        release: "gitlab-runner"
        heritage: "Helm"
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: gitlab-runner-gitlab-runner
      template:
        metadata:
          labels:
            app: gitlab-runner-gitlab-runner
            chart: gitlab-runner-0.21.1
            release: "gitlab-runner"
            heritage: "Helm"
          annotations:
            checksum/configmap: a6623303f6fcc3a043e87ea937bb8399d2d0068a901aa9c3419ed5c7a5afa9db
            checksum/secrets: 32c7d2c16918961b7b84a005680f748e774f61c6f4e4da30650d400d781bbb30
            prometheus.io/scrape: 'true'
            prometheus.io/port: '9252'
        spec:
          securityContext:
            runAsUser: 100
            fsGroup: 65533
          terminationGracePeriodSeconds: 3600
          initContainers:
          - name: configure
            command: ['sh', '/config/configure']
            image: gitlab/gitlab-runner:alpine-v13.4.1
            imagePullPolicy: "IfNotPresent"
            env:
    
            - name: CI_SERVER_URL
              value: "https://gitlab.qa.joaocunha.eu/"
            - name: CLONE_URL
              value: ""
            - name: RUNNER_REQUEST_CONCURRENCY
              value: "1"
            - name: RUNNER_EXECUTOR
              value: "kubernetes"
            - name: REGISTER_LOCKED
              value: "true"
            - name: RUNNER_TAG_LIST
              value: ""
            - name: RUNNER_OUTPUT_LIMIT
              value: "4096"
            - name: KUBERNETES_IMAGE
              value: "ubuntu:16.04"
    
            - name: KUBERNETES_PRIVILEGED
              value: "true"
    
            - name: KUBERNETES_NAMESPACE
              value: "gitlab"
            - name: KUBERNETES_POLL_TIMEOUT
              value: "180"
            - name: KUBERNETES_CPU_LIMIT
              value: ""
            - name: KUBERNETES_CPU_LIMIT_OVERWRITE_MAX_ALLOWED
              value: ""
            - name: KUBERNETES_MEMORY_LIMIT
              value: ""
            - name: KUBERNETES_MEMORY_LIMIT_OVERWRITE_MAX_ALLOWED
              value: ""
            - name: KUBERNETES_CPU_REQUEST
              value: ""
            - name: KUBERNETES_CPU_REQUEST_OVERWRITE_MAX_ALLOWED
              value: ""
            - name: KUBERNETES_MEMORY_REQUEST
              value: ""
            - name: KUBERNETES_MEMORY_REQUEST_OVERWRITE_MAX_ALLOWED
              value: ""
            - name: KUBERNETES_SERVICE_ACCOUNT
              value: ""
            - name: KUBERNETES_SERVICE_CPU_LIMIT
              value: ""
            - name: KUBERNETES_SERVICE_MEMORY_LIMIT
              value: ""
            - name: KUBERNETES_SERVICE_CPU_REQUEST
              value: ""
            - name: KUBERNETES_SERVICE_MEMORY_REQUEST
              value: ""
            - name: KUBERNETES_HELPER_CPU_LIMIT
              value: ""
            - name: KUBERNETES_HELPER_MEMORY_LIMIT
              value: ""
            - name: KUBERNETES_HELPER_CPU_REQUEST
              value: ""
            - name: KUBERNETES_HELPER_MEMORY_REQUEST
              value: ""
            - name: KUBERNETES_HELPER_IMAGE
              value: ""
            - name: KUBERNETES_PULL_POLICY
              value: ""
            volumeMounts:
            - name: runner-secrets
              mountPath: /secrets
              readOnly: false
            - name: scripts
              mountPath: /config
              readOnly: true
            - name: init-runner-secrets
              mountPath: /init-secrets
              readOnly: true
            resources:
              {}
          serviceAccountName: gitlab-runner-gitlab-runner
          containers:
          - name: gitlab-runner-gitlab-runner
            image: gitlab/gitlab-runner:alpine-v13.4.1
            imagePullPolicy: "IfNotPresent"
            lifecycle:
              preStop:
                exec:
                  command: ["/entrypoint", "unregister", "--all-runners"]
            command: ["/bin/bash", "/scripts/entrypoint"]
            env:
    
            - name: CI_SERVER_URL
              value: "https://gitlab.qa.joaocunha.eu/"
            - name: CLONE_URL
              value: ""
            - name: RUNNER_REQUEST_CONCURRENCY
              value: "1"
            - name: RUNNER_EXECUTOR
              value: "kubernetes"
            - name: REGISTER_LOCKED
              value: "true"
            - name: RUNNER_TAG_LIST
              value: ""
            - name: RUNNER_OUTPUT_LIMIT
              value: "4096"
            - name: KUBERNETES_IMAGE
              value: "ubuntu:16.04"
    
            - name: KUBERNETES_PRIVILEGED
              value: "true"
    
            - name: KUBERNETES_NAMESPACE
              value: "gitlab"
            - name: KUBERNETES_POLL_TIMEOUT
              value: "180"
            - name: KUBERNETES_CPU_LIMIT
              value: ""
            - name: KUBERNETES_CPU_LIMIT_OVERWRITE_MAX_ALLOWED
              value: ""
            - name: KUBERNETES_MEMORY_LIMIT
              value: ""
            - name: KUBERNETES_MEMORY_LIMIT_OVERWRITE_MAX_ALLOWED
              value: ""
            - name: KUBERNETES_CPU_REQUEST
              value: ""
            - name: KUBERNETES_CPU_REQUEST_OVERWRITE_MAX_ALLOWED
              value: ""
            - name: KUBERNETES_MEMORY_REQUEST
              value: ""
            - name: KUBERNETES_MEMORY_REQUEST_OVERWRITE_MAX_ALLOWED
              value: ""
            - name: KUBERNETES_SERVICE_ACCOUNT
              value: ""
            - name: KUBERNETES_SERVICE_CPU_LIMIT
              value: ""
            - name: KUBERNETES_SERVICE_MEMORY_LIMIT
              value: ""
            - name: KUBERNETES_SERVICE_CPU_REQUEST
              value: ""
            - name: KUBERNETES_SERVICE_MEMORY_REQUEST
              value: ""
            - name: KUBERNETES_HELPER_CPU_LIMIT
              value: ""
            - name: KUBERNETES_HELPER_MEMORY_LIMIT
              value: ""
            - name: KUBERNETES_HELPER_CPU_REQUEST
              value: ""
            - name: KUBERNETES_HELPER_MEMORY_REQUEST
              value: ""
            - name: KUBERNETES_HELPER_IMAGE
              value: ""
            - name: KUBERNETES_PULL_POLICY
              value: ""
            livenessProbe:
              exec:
                command: ["/bin/bash", "/scripts/check-live"]
              initialDelaySeconds: 60
              timeoutSeconds: 1
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 3
            readinessProbe:
              exec:
                command: ["/usr/bin/pgrep","gitlab.*runner"]
              initialDelaySeconds: 10
              timeoutSeconds: 1
              periodSeconds: 10
              successThreshold: 1
              failureThreshold: 3
            ports:
            - name: metrics
              containerPort: 9252
            volumeMounts:
            - name: runner-secrets
              mountPath: /secrets
            - name: etc-gitlab-runner
              mountPath: /home/gitlab-runner/.gitlab-runner
            - name: scripts
              mountPath: /scripts
            resources:
              {}
          volumes:
          - name: runner-secrets
            emptyDir:
              medium: "Memory"
          - name: etc-gitlab-runner
            emptyDir:
              medium: "Memory"
          - name: init-runner-secrets
            projected:
              sources:
                - secret:
                    name: "gitlab-runner-gitlab-runner"
                    items:
                      - key: runner-registration-token
                        path: runner-registration-token
                      - key: runner-token
                        path: runner-token
          - name: scripts
            configMap:
              name: gitlab-runner-gitlab-runner